### ISSUE TITLE
No matching version found for es-abstract@^1.18.0-next.1

### ISSUE THREAD

**Issue by exkira** [es-shims/object-is#12]
Hello,

First i'm sorry for my bad english.

Since today, I have this error message when I want install my dependencies : 

![image](https://user-images.githubusercontent.com/72197824/94795256-6578bf80-03dd-11eb-9257-ac12dc9b8601.png)

I see you have update your package with the last version of es-abstract, but it seems doesn't work =/.

Cordially

**Comment by academy-purpose** [comment]
Encountering the same error when installing the dependencies,
npm install is completely failing

![error](https://user-images.githubusercontent.com/71973021/94807291-12b6fc00-040d-11eb-9400-4deda0d711dc.png)

**Comment by academy-purpose** [comment]
Actually it was docker cache issue, hence cleared docker cache data and it works fine.

**Comment by ljharb** [comment]
Indeed; this is surely an issue with your local cache/npm registry/internet.

**Comment by jeaneto** [comment]
Good Afternoon ljhab, i'm with the same problem, but a i can move to another version of npm, I remove all dependencies and caches from npm, but, with de same problem, can you help me?

**Comment by ljharb** [comment]
@jeaneto can you provide more info? What exact error you’re getting, what node/npm versions, etc?
